#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

# NomaDamas 블로그에 GA4, Microsoft Clarity, Google Search Console, 네이버 서치어드바이저,
# Bing Webmaster Tools를 연결한다. 사람은 각 서비스에서 만들고 복사하고 버튼을 누르고,
# 이 스크립트는 형식 검사, 저장소 변수 등록, 재배포, 배포된 HTML 확인을 맡는다.
# 값은 전부 공개값(페이지 HTML에 그대로 나감)이라 secrets가 아니라 저장소 변수에 둔다.
# 실행: scripts/setup-seo-services.sh   (저장소 어디서든, gh 로그인 필요)

SITE_URL="https://nomadamas.github.io/"
cd "$(git rev-parse --show-toplevel)"
# 다시 실행할 때 기본값으로 쓰려고 입력값을 남겨 두는 파일. Astro가 읽지 않는 이름이라
# 로컬 개발 서버에 분석 태그가 붙지 않는다. .gitignore에 들어 있다.
ENV_FILE=".seo-services.env"

# 붙여넣은 값에서 토큰만 뽑는다. 메타 태그나 설치 코드를 통째로 붙여도 된다.
extract_token() {
  local raw="$1"
  if [[ "$raw" =~ content=\"([^\"]+)\" ]]; then printf '%s' "${BASH_REMATCH[1]}"; return; fi
  if [[ "$raw" =~ clarity\.ms/tag/([a-z0-9]+) ]]; then printf '%s' "${BASH_REMATCH[1]}"; return; fi
  if [[ "$raw" =~ \"script\",[[:space:]]*\"([a-z0-9]+)\" ]]; then printf '%s' "${BASH_REMATCH[1]}"; return; fi
  printf '%s' "$raw" | tr -d '[:space:]'
}

# ask_valid KEY "질문" REGEX — 형식이 맞을 때까지 다시 묻는다. 빈 값이면 이 서비스를 건너뛴다.
# 규칙은 src/components/SiteAnalytics.astro의 빌드 검사와 같다. 틀린 값은 배포 전에 여기서 걸러진다.
ask_valid() {
  local key="$1" prompt="$2" regex="$3" value
  while true; do
    ask "$key" "$prompt"
    value=$(extract_token "${!key}")
    if [[ -z "$value" ]]; then
      note "비워 두면 이 서비스는 건너뜁니다."
      printf -v "$key" '%s' ""
      return
    fi
    if [[ "$value" =~ $regex ]]; then
      printf -v "$key" '%s' "$value"
      write_env "$key" "$value"
      return
    fi
    warn "형식이 맞지 않습니다: $value"
  done
}

# main 브랜치의 배포 워크플로가 저장소 변수를 빌드에 넘기는지. 없으면 변수를 등록해도 반영되지 않는다.
main_passes_vars() {
  gh api "repos/{owner}/{repo}/contents/.github/workflows/deploy.yml?ref=main" \
    -H "Accept: application/vnd.github.raw" 2>/dev/null | grep -q "vars.PUBLIC_GA_MEASUREMENT_ID"
}

TOTAL_STAGES=10
BING_MODE=""

banner "NomaDamas 블로그 SEO, 방문 분석 연결"

# ── 1 ────────────────────────────────────────────────────────────────────
stage "Google Analytics 4: 측정 ID"
say "방문 통계용 GA4 속성을 만들고 측정 ID를 받아 옵니다."
open_url "https://analytics.google.com/analytics/web/"
step "왼쪽 아래 관리(Admin) -> 만들기(Create) -> 속성(Property)."
step "속성 이름 'NomaDamas 블로그', 시간대 대한민국, 통화 KRW로 만들고 다음 화면들을 진행합니다."
step "플랫폼은 웹(Web). 웹사이트 URL은 ${SITE_URL}, 스트림 이름은 '블로그'로 스트림을 만듭니다."
step "스트림 세부정보(Stream details)의 측정 ID(Measurement ID, G-로 시작)를 복사합니다."
note "화면 문구는 계정 언어에 따라 조금 다를 수 있어요. 막히면: https://support.google.com/analytics/answer/9304153"
note "설치 코드를 사이트에 붙이라는 안내가 나와도 무시하세요. 이 스크립트가 넣습니다."
ask_valid PUBLIC_GA_MEASUREMENT_ID "측정 ID를 붙여 넣으세요 (G-XXXX):" '^G-[A-Z0-9]+$'

# ── 2 ────────────────────────────────────────────────────────────────────
stage "Google Analytics 4: 브라우저 기록 기반 페이지뷰 끄기"
if [[ -n "$PUBLIC_GA_MEASUREMENT_ID" ]]; then
  say "이 블로그는 페이지를 새로 고치지 않고 넘깁니다(Astro ClientRouter). 넘길 때의 페이지뷰는"
  say "코드가 직접 보내므로, GA의 자동 수집을 끄지 않으면 페이지뷰가 두 번씩 잡힙니다."
  step "방금 만든 웹 스트림 화면의 향상된 측정(Enhanced measurement) 옆 톱니바퀴를 누릅니다."
  step "페이지 조회수(Page views) -> 고급 설정 표시(Show advanced settings)를 엽니다."
  step "'브라우저 기록 이벤트 기반 페이지 변경(Page changes based on browser history events)'을 끄고 저장합니다."
  note "'페이지 로드(Page loads)'는 켜 둔 채로 둡니다."
  pause "껐으면 Enter"
else
  note "GA4를 건너뛰어서 이 단계도 건너뜁니다."
fi

# ── 3 ────────────────────────────────────────────────────────────────────
stage "Microsoft Clarity: 프로젝트 ID"
say "클릭, 스크롤 히트맵과 세션 재생용 Clarity 프로젝트를 만듭니다."
open_url "https://clarity.microsoft.com/projects"
step "새 프로젝트(New project)를 만들고 웹사이트 URL에 ${SITE_URL}을 넣습니다."
step "설치 방법 화면(Settings -> Setup)에서 수동 설치(Install manually) -> Get tracking code를 누릅니다."
step "코드 끝의 \"script\", \"xxxxxxxxxx\" 에서 따옴표 안 값이 프로젝트 ID입니다. 코드 통째로 붙여도 됩니다."
note "코드를 사이트에 직접 붙이지 마세요. 이 스크립트가 넣습니다."
note "Clarity 약관상 18세 미만 대상 사이트에는 쓸 수 없습니다. 사용 사실은 /privacy/ 페이지에 자동으로 표시됩니다."
ask_valid PUBLIC_CLARITY_PROJECT_ID "프로젝트 ID 또는 설치 코드를 붙여 넣으세요:" '^[a-z0-9]+$'

# ── 4 ────────────────────────────────────────────────────────────────────
stage "Google Search Console: 소유확인 토큰"
say "구글 검색 색인과 노출 리포트를 보려면 사이트 소유를 확인해야 합니다."
open_url "https://search.google.com/search-console/welcome"
step "오른쪽 'URL 접두어(URL prefix)' 칸에 ${SITE_URL} 을 넣고 계속을 누릅니다."
step "다른 확인 방법 중 'HTML 태그'를 펼치고 메타 태그를 복사합니다."
warn "확인(Verify) 버튼은 아직 누르지 마세요. 배포가 끝난 뒤 8단계에서 누릅니다. 창은 열어 두세요."
note "github.io 주소라 '도메인' 속성은 쓸 수 없습니다. 막히면: https://support.google.com/webmasters/answer/9008080"
ask_valid PUBLIC_GOOGLE_SITE_VERIFICATION "메타 태그 또는 content 값을 붙여 넣으세요:" '^[A-Za-z0-9_-]+$'

# ── 5 ────────────────────────────────────────────────────────────────────
stage "네이버 서치어드바이저: 소유확인 토큰"
say "네이버 웹마스터도구에 사이트를 등록하고 소유확인용 HTML 태그를 받습니다."
open_url "https://searchadvisor.naver.com/console/board"
step "네이버로 로그인한 뒤 사이트 등록 칸에 ${SITE_URL%/} 을 넣습니다."
step "소유확인 방법에서 'HTML 태그'를 고르고 메타 태그를 복사합니다."
warn "소유확인 버튼은 아직 누르지 마세요. 8단계에서 누릅니다."
note "막히면: https://help.naver.com/service/30010/contents/17591"
ask_valid PUBLIC_NAVER_SITE_VERIFICATION "메타 태그 또는 content 값을 붙여 넣으세요:" '^[A-Za-z0-9_-]+$'

# ── 6 ────────────────────────────────────────────────────────────────────
stage "Bing Webmaster Tools: 연결 방식"
say "Bing은 Search Console에서 사이트를 가져오면 토큰 없이 자동으로 소유확인되고 사이트맵도 따라옵니다."
note "근거: https://www.bing.com/webmasters/help/add-and-verify-site-12184f8b"
if confirm "Search Console에서 가져오기로 할까요? (권장, 10단계에서 진행)"; then
  BING_MODE="import"
  PUBLIC_BING_SITE_VERIFICATION=""
else
  BING_MODE="meta"
  open_url "https://www.bing.com/webmasters"
  step "사이트를 수동으로 추가(Add your site manually)하고 ${SITE_URL} 을 넣습니다."
  step "확인 방법 중 메타 태그(Meta tag)를 고르고 <meta name=\"msvalidate.01\" ...> 를 복사합니다."
  warn "Verify는 아직 누르지 마세요. 8단계에서 누릅니다."
  ask_valid PUBLIC_BING_SITE_VERIFICATION "메타 태그 또는 content 값을 붙여 넣으세요:" '^[A-Za-z0-9]+$'
fi

# ── 7 ────────────────────────────────────────────────────────────────────
stage "저장소 변수 등록과 재배포"
VARS=(PUBLIC_GA_MEASUREMENT_ID PUBLIC_CLARITY_PROJECT_ID PUBLIC_GOOGLE_SITE_VERIFICATION
      PUBLIC_NAVER_SITE_VERIFICATION PUBLIC_BING_SITE_VERIFICATION)
TO_SET=()
for v in "${VARS[@]}"; do
  if [[ -n "${!v}" ]]; then TO_SET+=("$v"); say "$v = ${!v}"; fi
done
if (( ${#TO_SET[@]} == 0 )); then
  warn "입력한 값이 없습니다. 등록할 것이 없어 끝냅니다."
  finish; exit 0
fi
if ! command -v gh >/dev/null 2>&1 || ! gh auth status >/dev/null 2>&1; then
  warn "gh가 없거나 로그인되어 있지 않습니다. gh auth login 후 다시 실행하세요. 입력값은 ${ENV_FILE}에 남아 있습니다."
  SKIPPED+=("저장소 변수 등록과 재배포 (gh auth login 후 재실행)")
  finish; exit 1
fi
if ! main_passes_vars; then
  warn "main의 배포 워크플로가 아직 이 변수들을 빌드에 넘기지 않습니다."
  warn "SEO 서비스 PR을 머지한 뒤 다시 실행하세요. 입력값은 ${ENV_FILE}에 남아 있어 Enter만 누르면 됩니다."
  SKIPPED+=("저장소 변수 등록과 재배포 (PR 머지 후 재실행)")
  finish; exit 0
fi
if ! confirm "위 ${#TO_SET[@]}개를 저장소 변수로 등록하고 main을 다시 배포할까요?"; then
  SKIPPED+=("저장소 변수 등록과 재배포")
  finish; exit 0
fi
for v in "${TO_SET[@]}"; do set_var "$v" "${!v}"; done

gh workflow run deploy.yml --ref main >/dev/null
say "배포를 시작했습니다. 끝날 때까지 기다립니다."
sleep 8
RUN_ID=$(gh run list --workflow deploy.yml --branch main --event workflow_dispatch --limit 1 \
  --json databaseId -q '.[0].databaseId')
if ! gh run watch "$RUN_ID" --exit-status >/dev/null; then
  warn "배포가 실패했습니다: gh run view $RUN_ID --log-failed"
  SKIPPED+=("배포 실패 원인 확인 (gh run view $RUN_ID --log-failed)")
  finish; exit 1
fi
printf '  %s✓ 배포 완료%s\n' "$GREEN" "$RESET"

# Pages CDN이 잠깐 이전 HTML을 줄 수 있어서 캐시를 피하는 쿼리를 붙여 몇 번 다시 본다.
MISSING=("${TO_SET[@]}")
for _try in 1 2 3 4 5 6; do
  HTML=$(curl -fsSL "${SITE_URL}?v=$(date +%s)" || true)
  STILL=()
  for v in "${MISSING[@]}"; do
    [[ "$HTML" == *"${!v}"* ]] || STILL+=("$v")
  done
  MISSING=("${STILL[@]+"${STILL[@]}"}")
  (( ${#MISSING[@]} == 0 )) && break
  sleep 10
done
for v in "${TO_SET[@]}"; do
  if [[ " ${MISSING[*]+"${MISSING[*]}"} " == *" $v "* ]]; then
    warn "배포된 HTML에서 $v 값을 찾지 못했습니다."
    SKIPPED+=("$v 반영 확인 (curl -s $SITE_URL | grep ${!v})")
  else
    printf '  %s✓ 반영됨%s %s\n' "$GREEN" "$RESET" "$v"
  fi
done
pause "Enter로 다음 단계"

# ── 8 ────────────────────────────────────────────────────────────────────
stage "소유확인 버튼 누르기"
say "태그가 배포됐으니 각 서비스에서 확인 버튼을 누릅니다."
if [[ -n "$PUBLIC_GOOGLE_SITE_VERIFICATION" ]]; then
  step "Search Console: 4단계에서 열어 둔 HTML 태그 화면에서 확인(Verify)을 누릅니다."
  note "창을 닫았다면 같은 주소로 속성을 다시 추가하고 HTML 태그의 확인을 누르면 됩니다."
  open_url "https://search.google.com/search-console/welcome"
  pause "확인됐으면 Enter"
fi
if [[ -n "$PUBLIC_NAVER_SITE_VERIFICATION" ]]; then
  open_url "https://searchadvisor.naver.com/console/board"
  step "네이버: 사이트 목록에서 ${SITE_URL%/} 의 소유확인을 누릅니다."
  pause "확인됐으면 Enter"
fi
if [[ "$BING_MODE" == "meta" && -n "$PUBLIC_BING_SITE_VERIFICATION" ]]; then
  open_url "https://www.bing.com/webmasters"
  step "Bing: 6단계의 메타 태그 화면에서 Verify를 누릅니다."
  pause "확인됐으면 Enter"
fi

# ── 9 ────────────────────────────────────────────────────────────────────
stage "사이트맵과 RSS 제출"
say "새 글을 빨리 찾도록 사이트맵과 RSS 주소를 알려 줍니다."
if [[ -n "$PUBLIC_GOOGLE_SITE_VERIFICATION" ]]; then
  open_url "https://search.google.com/search-console/sitemaps?resource_id=${SITE_URL}"
  step "Search Console Sitemaps: 'sitemap-index.xml'을 입력하고 제출, 이어서 'rss.xml'도 제출합니다."
  pause "제출했으면 Enter"
fi
if [[ -n "$PUBLIC_NAVER_SITE_VERIFICATION" ]]; then
  open_url "https://searchadvisor.naver.com/console/board"
  step "네이버: 사이트를 고르고 요청 -> 사이트맵 제출에 ${SITE_URL}sitemap-index.xml 을 제출합니다."
  step "요청 -> RSS 제출에 ${SITE_URL}rss.xml 을 제출합니다."
  note "안내: https://searchadvisor.naver.com/guide/request-feed"
  pause "제출했으면 Enter"
fi

# ── 10 ───────────────────────────────────────────────────────────────────
stage "Bing Webmaster Tools 마무리"
if [[ "$BING_MODE" == "import" ]]; then
  if [[ -z "$PUBLIC_GOOGLE_SITE_VERIFICATION" ]]; then
    warn "Search Console을 건너뛰어서 가져오기를 할 수 없습니다. 다시 실행해 메타 태그 방식을 고르세요."
    SKIPPED+=("Bing 연결")
  else
    open_url "https://www.bing.com/webmasters"
    step "'Search Console에서 가져오기(Import from Google Search Console)'를 고르고 구글 계정 접근을 허용합니다."
    step "목록에서 ${SITE_URL} 을 고르고 가져오기(Import)를 누릅니다. 사이트맵도 함께 넘어옵니다."
    pause "가져왔으면 Enter"
  fi
elif [[ -n "$PUBLIC_BING_SITE_VERIFICATION" ]]; then
  open_url "https://www.bing.com/webmasters"
  step "Bing Sitemaps 메뉴에서 ${SITE_URL}sitemap-index.xml 을 제출합니다."
  pause "제출했으면 Enter"
else
  note "Bing을 건너뛰었습니다."
fi
note "색인과 리포트가 채워지기까지는 며칠 걸립니다. Bing은 보통 48시간이라고 안내합니다."

finish
